### ISSUE TITLE
`Codecov` instead of `Smokeshow`

### ISSUE THREAD

**Issue by AshGw** [AshGw/ts-roids#58]
### New feature motivation

_

### New feature description

_

### New feature implementation

````yaml
name: 'Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/yarn-install@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Test types'
        shell: bash
        #language=sh
        run: |
          yarn test:types

      - name: 'Run tests'
        shell: bash
        #language=sh
        run: |
          ARGS="${{ matrix.node-version == vars.NODE_VERSION && '--coverage' || '' }}"

          yarn test:run $ARGS

      - name: 'Upload coverage'
        uses: codecov/codecov-action@v3
        if: matrix.node-version == vars.NODE_VERSION
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
````
